# 389. Find the Difference

=begin
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 
Seen this question in a real interview before?
1/5
=end

# @param {String} s
# @param {String} t
# @return {Character}
def find_the_difference(s, t)
    result = 0

    s.each_byte { |ch| result ^= ch }
    t.each_byte { |ch| result ^= ch }

    result.chr
end

# Alternate (HashMap — not optimal but acceptable)

def find_the_difference(s, t)
  count = Hash.new(0)

  s.each_char { |c| count[c] += 1 }
  t.each_char { |c| count[c] -= 1 }

  count.key(-1)
end
